export type GroupAudience = "Everyone" | "Men" | "Women" | "Youth"

export type GroupLanguage = "en" | "ta" | "bilingual"
export type GroupAge = "all" | "kids" | "youth" | "adults"

export type SmallGroup = {
  id: string
  nameEn: string
  nameTa: string
  audience: GroupAudience
  languages: GroupLanguage[]
  age: GroupAge
  interests: string[]
  meetingTimeEn: string
  meetingTimeTa: string
  area?: string
  locationEn: string
  locationTa: string
  descriptionEn: string
  descriptionTa: string
  contactName: string
  contactEmail: string
}

export const smallGroups: SmallGroup[] = [
  {
    id: "g1",
    nameEn: "Grace Gathering (Mississauga)",
    nameTa: "Ã Â®Å¡Ã Â®Â¿Ã Â®Â±Ã Â¯Â Ã Â®•Ã Â¯ÂÃ Â®Â´Ã Â¯Â (Ã Â®Â®Ã Â®Â¿Ã Â®Å¡Ã Â®Â¿Ã Â®Å¡Ã Â®Â¾Ã Â®•Ã Â®Â¾)",
    audience: "Everyone",
    languages: ["bilingual"],
    age: "all",
    interests: ["Prayer", "Bible study", "Community"],
    meetingTimeEn: "Wednesdays • 7:30 PM",
    meetingTimeTa: "Ã Â®ÂªÃ Â¯ÂÃ Â®Â¤Ã Â®Â©Ã Â¯Â • 7:30 PM",
    area: "Mississauga",
    locationEn: "Home group (address shared after RSVP)",
    locationTa: "Ã Â®ÂµÃ Â¯â‚¬Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â¯Â Ã Â®•Ã Â¯ÂÃ Â®Â´Ã Â¯Â (Ã Â®ÂªÃ Â®Â¤Ã Â®Â¿Ã Â®ÂµÃ Â¯ÂÃ Â®•Ã Â¯ÂÃ Â®•Ã Â¯ÂÃ Â®ÂªÃ Â¯Â Ã Â®ÂªÃ Â®Â¿Ã Â®Â±Ã Â®•Ã Â¯Â Ã Â®Â®Ã Â¯ÂÃ Â®•Ã Â®ÂµÃ Â®Â°Ã Â®Â¿)",
    descriptionEn: "Prayer, a short Bible study, and time to connect.",
    descriptionTa: "Ã Â®Å“Ã Â¯â€ Ã Â®ÂªÃ Â®Â®Ã Â¯Â, Ã Â®Å¡Ã Â¯ÂÃ Â®Â°Ã Â¯ÂÃ Â®•Ã Â¯ÂÃ Â®•Ã Â®Â®Ã Â®Â¾Ã Â®Â© Ã Â®ÂµÃ Â¯â€¡Ã Â®Â¤Ã Â®Â¾Ã Â®•Ã Â®Â®Ã Â®ÂªÃ Â¯Â Ã Â®ÂªÃ Â®Å¸Ã Â®Â¿Ã Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â¯Â, Ã Â®â€¡Ã Â®Â£Ã Â¯Ë†Ã Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â¯Â Ã Â®Â¨Ã Â¯â€¡Ã Â®Â°Ã Â®Â®Ã Â¯Â.",
    contactName: "Small Groups Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g3",
    nameEn: "Women's Prayer Circle",
    nameTa: "Ã Â®ÂªÃ Â¯â€ Ã Â®Â£Ã Â¯ÂÃ Â®•Ã Â®Â³Ã Â¯Â Ã Â®Å“Ã Â¯â€ Ã Â®Âª Ã Â®•Ã Â¯ÂÃ Â®Â´Ã Â¯Â",
    audience: "Women",
    languages: ["ta", "bilingual"],
    age: "adults",
    interests: ["Prayer", "Encouragement", "Support"],
    meetingTimeEn: "Tuesdays • 8:00 PM",
    meetingTimeTa: "Ã Â®Å¡Ã Â¯â€ Ã Â®ÂµÃ Â¯ÂÃ Â®ÂµÃ Â®Â¾Ã Â®Â¯Ã Â¯Â • 8:00 PM",
    area: "Online",
    locationEn: "Online (Zoom)",
    locationTa: "Ã Â®â€ Ã Â®Â©Ã Â¯ÂÃ Â®Â²Ã Â¯Ë†Ã Â®Â©Ã Â¯Â (Zoom)",
    descriptionEn: "Encouragement and prayer with other women.",
    descriptionTa: "Ã Â®â€°Ã Â®Â±Ã Â¯ÂÃ Â®Å¡Ã Â®Â¾Ã Â®•Ã Â®Â®Ã Â¯ÂÃ Â®Â®Ã Â¯Â Ã Â®Å“Ã Â¯â€ Ã Â®ÂªÃ Â®Â®Ã Â¯ÂÃ Â®Â®Ã Â¯Â.",
    contactName: "Women's Ministry Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g4",
    nameEn: "Men's Bible Study",
    nameTa: "Men's Bible Study",
    audience: "Men",
    languages: ["en", "bilingual"],
    age: "adults",
    interests: ["Bible study", "Brotherhood", "Prayer"],
    meetingTimeEn: "Thursdays • 7:30 PM",
    meetingTimeTa: "Thursdays • 7:30 PM",
    area: "Mississauga",
    locationEn: "Home group (address shared after RSVP)",
    locationTa: "Home group (address shared after RSVP)",
    descriptionEn: "A practical Bible study and time to pray together as men.",
    descriptionTa: "A practical Bible study and time to pray together as men.",
    contactName: "Men's Ministry Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g5",
    nameEn: "Tamil Bible Study (Online)",
    nameTa: "Tamil Bible Study (Online)",
    audience: "Everyone",
    languages: ["ta", "bilingual"],
    age: "adults",
    interests: ["Bible study", "Discipleship", "Prayer"],
    meetingTimeEn: "Mondays • 8:00 PM",
    meetingTimeTa: "Mondays • 8:00 PM",
    area: "Online",
    locationEn: "Online (Zoom)",
    locationTa: "Online (Zoom)",
    descriptionEn: "A Tamil-focused Bible study with space for questions and prayer.",
    descriptionTa: "A Tamil-focused Bible study with space for questions and prayer.",
    contactName: "Small Groups Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g6",
    nameEn: "Newcomers Connect",
    nameTa: "Newcomers Connect",
    audience: "Everyone",
    languages: ["en", "ta", "bilingual"],
    age: "adults",
    interests: ["Welcome", "Next steps", "Friendship"],
    meetingTimeEn: "Sundays • after service (monthly)",
    meetingTimeTa: "Sundays • after service (monthly)",
    area: "On-site",
    locationEn: "On-site (Lobby / Welcome area)",
    locationTa: "On-site (Lobby / Welcome area)",
    descriptionEn: "Meet leaders, ask questions, and learn simple next steps to get connected.",
    descriptionTa: "Meet leaders, ask questions, and learn simple next steps to get connected.",
    contactName: "Welcome Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g7",
    nameEn: "Family Fellowship",
    nameTa: "Family Fellowship",
    audience: "Everyone",
    languages: ["bilingual"],
    age: "all",
    interests: ["Families", "Community", "Prayer"],
    meetingTimeEn: "Saturdays • 6:00 PM (bi-weekly)",
    meetingTimeTa: "Saturdays • 6:00 PM (bi-weekly)",
    area: "Mississauga",
    locationEn: "Home group (address shared after RSVP)",
    locationTa: "Home group (address shared after RSVP)",
    descriptionEn: "A relaxed gathering with a short devotional, prayer, and fellowship for families.",
    descriptionTa: "A relaxed gathering with a short devotional, prayer, and fellowship for families.",
    contactName: "Small Groups Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g8",
    nameEn: "Youth Hangout + Devotional",
    nameTa: "Youth Hangout + Devotional",
    audience: "Youth",
    languages: ["en", "bilingual"],
    age: "youth",
    interests: ["Youth", "Friendship", "Discipleship"],
    meetingTimeEn: "Saturdays • 5:00 PM",
    meetingTimeTa: "Saturdays • 5:00 PM",
    area: "On-site",
    locationEn: "On-site (Youth room)",
    locationTa: "On-site (Youth room)",
    descriptionEn: "Games, snacks, a short devotional, and small group discussion.",
    descriptionTa: "Games, snacks, a short devotional, and small group discussion.",
    contactName: "Youth Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g9",
    nameEn: "Prayer & Fasting (Online)",
    nameTa: "Prayer & Fasting (Online)",
    audience: "Everyone",
    languages: ["en", "ta", "bilingual"],
    age: "adults",
    interests: ["Prayer", "Fasting", "Intercession"],
    meetingTimeEn: "Tuesdays • 6:30 AM",
    meetingTimeTa: "Tuesdays • 6:30 AM",
    area: "Online",
    locationEn: "Online (Zoom)",
    locationTa: "Online (Zoom)",
    descriptionEn: "A short, focused time of prayer to start the day together (come as you are).",
    descriptionTa: "A short, focused time of prayer to start the day together (come as you are).",
    contactName: "Prayer Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g10",
    nameEn: "Care & Encouragement Circle",
    nameTa: "Care & Encouragement Circle",
    audience: "Everyone",
    languages: ["bilingual"],
    age: "adults",
    interests: ["Care", "Encouragement", "Support"],
    meetingTimeEn: "Sundays • 6:30 PM (monthly)",
    meetingTimeTa: "Sundays • 6:30 PM (monthly)",
    area: "Online",
    locationEn: "Online (Zoom)",
    locationTa: "Online (Zoom)",
    descriptionEn: "A gentle space for encouragement, listening, and prayer during challenging seasons.",
    descriptionTa: "A gentle space for encouragement, listening, and prayer during challenging seasons.",
    contactName: "Care Team",
    contactEmail: "info@praisetabernacle.ca",
  },
]

