export type GroupAudience = "Everyone" | "Men" | "Women" | "Youth"

export type GroupLanguage = "en" | "ta" | "bilingual"
export type GroupAge = "all" | "kids" | "youth" | "adults"

export type SmallGroup = {
  id: string
  nameEn: string
  nameTa: string
  audience: GroupAudience
  languages: GroupLanguage[]
  age: GroupAge
  interests: string[]
  meetingTimeEn: string
  meetingTimeTa: string
  area?: string
  locationEn: string
  locationTa: string
  descriptionEn: string
  descriptionTa: string
  contactName: string
  contactEmail: string
}

export const smallGroups: SmallGroup[] = [
  {
    id: "g1",
    nameEn: "Grace Gathering (Mississauga)",
    nameTa: "à®šà®¿à®±à¯ à®•à¯à®´à¯ (à®®à®¿à®šà®¿à®šà®¾à®•à®¾)",
    audience: "Everyone",
    languages: ["bilingual"],
    age: "all",
    interests: ["Prayer", "Bible study", "Community"],
    meetingTimeEn: "Wednesdays â€¢ 7:30 PM",
    meetingTimeTa: "à®ªà¯à®¤à®©à¯ â€¢ 7:30 PM",
    area: "Mississauga",
    locationEn: "Home group (address shared after RSVP)",
    locationTa: "à®µà¯€à®Ÿà¯à®Ÿà¯ à®•à¯à®´à¯ (à®ªà®¤à®¿à®µà¯à®•à¯à®•à¯à®ªà¯ à®ªà®¿à®±à®•à¯ à®®à¯à®•à®µà®°à®¿)",
    descriptionEn: "Prayer, a short Bible study, and time to connect.",
    descriptionTa: "à®œà¯†à®ªà®®à¯, à®šà¯à®°à¯à®•à¯à®•à®®à®¾à®© à®µà¯‡à®¤à®¾à®•à®®à®ªà¯ à®ªà®Ÿà®¿à®ªà¯à®ªà¯, à®‡à®£à¯ˆà®ªà¯à®ªà¯ à®¨à¯‡à®°à®®à¯.",
    contactName: "Small Groups Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g3",
    nameEn: "Womenâ€™s Prayer Circle",
    nameTa: "à®ªà¯†à®£à¯à®•à®³à¯ à®œà¯†à®ª à®•à¯à®´à¯",
    audience: "Women",
    languages: ["ta", "bilingual"],
    age: "adults",
    interests: ["Prayer", "Encouragement", "Support"],
    meetingTimeEn: "Tuesdays â€¢ 8:00 PM",
    meetingTimeTa: "à®šà¯†à®µà¯à®µà®¾à®¯à¯ â€¢ 8:00 PM",
    area: "Online",
    locationEn: "Online (Zoom)",
    locationTa: "à®†à®©à¯à®²à¯ˆà®©à¯ (Zoom)",
    descriptionEn: "Encouragement and prayer with other women.",
    descriptionTa: "à®‰à®±à¯à®šà®¾à®•à®®à¯à®®à¯ à®œà¯†à®ªà®®à¯à®®à¯.",
    contactName: "Womenâ€™s Ministry Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g4",
    nameEn: "Men's Bible Study",
    nameTa: "Men's Bible Study",
    audience: "Men",
    languages: ["en", "bilingual"],
    age: "adults",
    interests: ["Bible study", "Brotherhood", "Prayer"],
    meetingTimeEn: "Thursdays â€¢ 7:30 PM",
    meetingTimeTa: "Thursdays â€¢ 7:30 PM",
    area: "Mississauga",
    locationEn: "Home group (address shared after RSVP)",
    locationTa: "Home group (address shared after RSVP)",
    descriptionEn: "A practical Bible study and time to pray together as men.",
    descriptionTa: "A practical Bible study and time to pray together as men.",
    contactName: "Men's Ministry Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g5",
    nameEn: "Tamil Bible Study (Online)",
    nameTa: "Tamil Bible Study (Online)",
    audience: "Everyone",
    languages: ["ta", "bilingual"],
    age: "adults",
    interests: ["Bible study", "Discipleship", "Prayer"],
    meetingTimeEn: "Mondays â€¢ 8:00 PM",
    meetingTimeTa: "Mondays â€¢ 8:00 PM",
    area: "Online",
    locationEn: "Online (Zoom)",
    locationTa: "Online (Zoom)",
    descriptionEn: "A Tamil-focused Bible study with space for questions and prayer.",
    descriptionTa: "A Tamil-focused Bible study with space for questions and prayer.",
    contactName: "Small Groups Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g6",
    nameEn: "Newcomers Connect",
    nameTa: "Newcomers Connect",
    audience: "Everyone",
    languages: ["en", "ta", "bilingual"],
    age: "adults",
    interests: ["Welcome", "Next steps", "Friendship"],
    meetingTimeEn: "Sundays â€¢ after service (monthly)",
    meetingTimeTa: "Sundays â€¢ after service (monthly)",
    area: "On-site",
    locationEn: "On-site (Lobby / Welcome area)",
    locationTa: "On-site (Lobby / Welcome area)",
    descriptionEn: "Meet leaders, ask questions, and learn simple next steps to get connected.",
    descriptionTa: "Meet leaders, ask questions, and learn simple next steps to get connected.",
    contactName: "Welcome Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g7",
    nameEn: "Family Fellowship",
    nameTa: "Family Fellowship",
    audience: "Everyone",
    languages: ["bilingual"],
    age: "all",
    interests: ["Families", "Community", "Prayer"],
    meetingTimeEn: "Saturdays â€¢ 6:00 PM (bi-weekly)",
    meetingTimeTa: "Saturdays â€¢ 6:00 PM (bi-weekly)",
    area: "Mississauga",
    locationEn: "Home group (address shared after RSVP)",
    locationTa: "Home group (address shared after RSVP)",
    descriptionEn: "A relaxed gathering with a short devotional, prayer, and fellowship for families.",
    descriptionTa: "A relaxed gathering with a short devotional, prayer, and fellowship for families.",
    contactName: "Small Groups Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g8",
    nameEn: "Youth Hangout + Devotional",
    nameTa: "Youth Hangout + Devotional",
    audience: "Youth",
    languages: ["en", "bilingual"],
    age: "youth",
    interests: ["Youth", "Friendship", "Discipleship"],
    meetingTimeEn: "Saturdays â€¢ 5:00 PM",
    meetingTimeTa: "Saturdays â€¢ 5:00 PM",
    area: "On-site",
    locationEn: "On-site (Youth room)",
    locationTa: "On-site (Youth room)",
    descriptionEn: "Games, snacks, a short devotional, and small group discussion.",
    descriptionTa: "Games, snacks, a short devotional, and small group discussion.",
    contactName: "Youth Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g9",
    nameEn: "Prayer & Fasting (Online)",
    nameTa: "Prayer & Fasting (Online)",
    audience: "Everyone",
    languages: ["en", "ta", "bilingual"],
    age: "adults",
    interests: ["Prayer", "Fasting", "Intercession"],
    meetingTimeEn: "Tuesdays â€¢ 6:30 AM",
    meetingTimeTa: "Tuesdays â€¢ 6:30 AM",
    area: "Online",
    locationEn: "Online (Zoom)",
    locationTa: "Online (Zoom)",
    descriptionEn: "A short, focused time of prayer to start the day together (come as you are).",
    descriptionTa: "A short, focused time of prayer to start the day together (come as you are).",
    contactName: "Prayer Team",
    contactEmail: "info@praisetabernacle.ca",
  },
  {
    id: "g10",
    nameEn: "Care & Encouragement Circle",
    nameTa: "Care & Encouragement Circle",
    audience: "Everyone",
    languages: ["bilingual"],
    age: "adults",
    interests: ["Care", "Encouragement", "Support"],
    meetingTimeEn: "Sundays â€¢ 6:30 PM (monthly)",
    meetingTimeTa: "Sundays â€¢ 6:30 PM (monthly)",
    area: "Online",
    locationEn: "Online (Zoom)",
    locationTa: "Online (Zoom)",
    descriptionEn: "A gentle space for encouragement, listening, and prayer during challenging seasons.",
    descriptionTa: "A gentle space for encouragement, listening, and prayer during challenging seasons.",
    contactName: "Care Team",
    contactEmail: "info@praisetabernacle.ca",
  },
]
